exports.user_seeders = [
    {
        first_name: "Lucio",
        last_name: "User Seeder",
        username: "lucio_seeder",
        password: "Contra111",
        birthdate: "2050-01-01",
        picture: "https://cdn2.vectorstock.com/i/thumb-large/04/96/user-icon-vector-19240496.jpg",
        country: "Colombia",
        email: "user1@seeder.com",
        phone: "4674139642",
        favorite: [],
        following: [],
    },
    {
        first_name: "Diego",
        last_name: "User Seeder",
        username: "Diego_seeder",
        password: "Contrasena123",
        birthdate: "2040-01-01",
        picture: "https://cdn2.vectorstock.com/i/thumb-large/04/96/user-icon-vector-19240496.jpg",
        country: "Colombia",
        email: "diegogilhz@gmail.com",
        phone: "9992327442",
        favorite: [],
        following: [],
    },
    {
        first_name: "Viviana Abigail",
        last_name: "Cruz",
        username: "Abigailcruz1202",
        password: "Ejemplo123",
        birthdate: "2000-02-12",
        picture: "https://cdn2.vectorstock.com/i/thumb-large/04/96/user-icon-vector-19240496.jpg",
        country: "Argentina",
        email: "cruzabi994@gmail.com",
        phone: "541144191084",
        favorite: [],
        following: [],
    },
    {
        first_name: "LEONARDO",
        last_name: "FERNANDEZ",
        username: "u2902486@unimilitar.edu.co ",
        password: "leofer09",
        birthdate: "2021-10-18",
        picture: "https://cdn2.vectorstock.com/i/thumb-large/04/96/user-icon-vector-19240496.jpg",
        country: "Colombia",
        email: "u2902486@unimilitar.edu.co",
        phone: "3164500088",
        favorite: [],
        following: [],
    },
    {
        first_name: "gerardo",
        last_name: "pedraza",
        username: "ger",
        password: "123",
        birthdate: "2000-02-12",
        picture: "https://cdn2.vectorstock.com/i/thumb-large/04/96/user-icon-vector-19240496.jpg",
        country: "México",
        email: "artistaudiovisual@gmail.com",
        phone: "541144191086",
        favorite: [],
        following: [],
    },
    {
        first_name: "olivia dafne",
        last_name: "Serrano cruz",
        username: "Dafnecita",
        password: "Yaotzin29416",
        birthdate: "1988-06-19",
        picture: "https://cdn2.vectorstock.com/i/thumb-large/04/96/user-icon-vector-19240496.jpg",
        country: "México",
        email: "tieta922002@hotmail.com",
        phone: "524612917348",
        favorite: [],
        following: [],
    }
]

exports.promoter_seeders = [
    {
        legal_name: "Lucio el Seeder",
        business_name: "Promoter Seeder",
        tax_id: "42569782549",
        promoter_name: "Lucio Promoter Seeder",
        picture: "https://cdn2.vectorstock.com/i/thumb-large/04/96/user-icon-vector-19240496.jpg",
        phone: "5731347829472",
        email: "promoter1@seeder.com",
        password: "Contra222",
        business_type: "Estadio",
        address: "Seeder 34782",
        authorized: false,
        followed_by: []
},
]